package com.pod2.elevator.core.events;

/**
 * Classifies an event by the way in which it was created.
 * 
 */
public enum EventSource {

	/**
	 * Event was generated by the simulator during execution.
	 */
	Generated,

	/**
	 * Event was inserted into the running simulation through the web interface.
	 */
	Inserted,

	/**
	 * Event was specified in the template used to initialise the simulation.
	 */
	Template
	
}
